name: Lambda

on:
  push:
  workflow_dispatch:

jobs:
  package:
    name: Lambda Package
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
        cache: pip
        cache-dependency-path: |
          **/pyproject.toml
          **/requirements*.txt

    - name: Prepare Python env
      run: |
        python -m pip install -U pip setuptools wheel

    - name: Make lambda package
      run: |
        make lambda-package

    - name: Create artifact
      uses: actions/upload-artifact@v4
      with:
        name: fair-wizard-integration-sdk-lambda-layer.zip
        path: fair-wizard-integration-sdk-lambda-layer.zip
        retention-days: 90
