name: Test

on:
  push:

jobs:
  run_tests:
    name: "Run tests"
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v4

    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: "Install dependencies"
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: "Install package"
      run: |
        pip install .

    - name: "Run tests"
      run: |
        for testdir in "$(pwd)/tests/"*; do
          cd $testdir
          echo "Running test.py in $testdir"
          python test.py
          echo "----------------------------------"
        done

  generate_docs:
    name: "Generate docs"
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v4

    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: "Install dependencies"
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: "Install package"
      run: |
        pip install .

    - name: "Install docs dependencies"
      run: |
        cd docs
        pip install -r requirements.txt

    - name: "Generate docs"
      run: |
        cd docs
        make html
